before_install:
    # init xvfb
    # http://docs.travis-ci.com/user/gui-and-headless-browsers/
    - export DISPLAY=:99.0 && sh -e /etc/init.d/xvfb start
branches:
    only:
    - alpha
    - beta
    - cron
    - docker.base
    - docker.latest
    - master
    - publish
    - task
env:
    global:
    # this value is auto-created by shTravisCryptoAesEncryptYml
    - secure: auKUJr7Rs8D/hDB9dlZHtR0kkZSyZ/4vssPUjLhweHKDqTlz42sgMUZOUMKZFqeJHdWjZ2Ucowb3Vb+CjjfdkUc/qKiIlH69B1ohZIKTq9B+aNfs0X5Rtk3z5lu0L04QMFLkkc8of+4Sjj9tAfqcpOtxbp1lbYK/eAlIxrnIwxlNJV3cYSudzEzKlCGoOnCuRtChhDD2No6diqv1aRjKxElsDqLU2B7T/BYvybJgVurVpMuFJZX7r0ntW5XDwid1jpTCbLHzbniBJ6sGUUAmgf+/BZ+wGMhTfHnxr14SY0iWtjiVG/QHScRcQnV7gGkYPV6nAQkxFaFmlVFIDhDalbWHp6TLbZneCJoMM5tQqMngoeD8CXhzMGL81Psqvnfgu/YtxNsV/mFRTVfDXA8S01pAh8i+ydMpyBzLhAmzBZ0bH+rvrvfYauAgq84NfW7UKEDrgDr+J2xuHmcVUN5UkEaenMrS5u22LMKH0VXpHaSgN90VWQtUujsTpqZI7g9z07kdTo4TCksXOrGuzwnmsmhivfjWKwfHIKRa4MH2b0eWUGTBDj8R6fY+nGfwKulHZxrorqGCly+B02QJp5nMcO5UNa2ikVDobmc5QTOTT2jXyqWm4NyQaqhzeYkOODBFY7zKprBHw+7CmkqVqgpTLbOoXRwcrWFECYdwa7ScFuI= # CRYPTO_AES_KEY
    # this value is auto-created by shTravisCryptoAesEncryptYml

language:
    - node_js
node_js:
    - 6
    # - node
script:
    - npm run build-ci
services:
    - docker
# http://docs.travis-ci.com/user/workers/container-based-infrastructure
sudo:
    false
